-- 1. URL pool
CREATE TABLE public.brezzels_comment_targets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  url text NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.brezzels_comment_targets TO authenticated;
GRANT ALL ON public.brezzels_comment_targets TO service_role;
ALTER TABLE public.brezzels_comment_targets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "auth read targets" ON public.brezzels_comment_targets FOR SELECT TO authenticated USING (true);
CREATE POLICY "admin manage targets" ON public.brezzels_comment_targets FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'super_admin'));

-- 2. Assignments / history
CREATE TABLE public.brezzels_comment_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_id uuid NOT NULL REFERENCES public.brezzels_comment_targets(id) ON DELETE CASCADE,
  assigned_date date NOT NULL DEFAULT (now() AT TIME ZONE 'Europe/Berlin')::date,
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(user_id, target_id, assigned_date)
);
CREATE INDEX brezzels_assignments_user_date_idx ON public.brezzels_comment_assignments(user_id, assigned_date);
CREATE INDEX brezzels_assignments_user_target_idx ON public.brezzels_comment_assignments(user_id, target_id);

GRANT SELECT, INSERT, UPDATE ON public.brezzels_comment_assignments TO authenticated;
GRANT ALL ON public.brezzels_comment_assignments TO service_role;
ALTER TABLE public.brezzels_comment_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user sees own" ON public.brezzels_comment_assignments FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "user updates own" ON public.brezzels_comment_assignments FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "user inserts own" ON public.brezzels_comment_assignments FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- 3. RPC: get or assign today's targets for current user
CREATE OR REPLACE FUNCTION public.get_brezzels_comment_targets(p_count int DEFAULT 20)
RETURNS TABLE(id uuid, url text, completed boolean)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_today date := (now() AT TIME ZONE 'Europe/Berlin')::date;
  v_existing int;
  v_needed int;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT count(*) INTO v_existing
  FROM brezzels_comment_assignments
  WHERE user_id = v_user AND assigned_date = v_today;

  v_needed := GREATEST(0, p_count - v_existing);

  IF v_needed > 0 THEN
    INSERT INTO brezzels_comment_assignments (user_id, target_id, assigned_date)
    SELECT v_user, t.id, v_today
    FROM brezzels_comment_targets t
    LEFT JOIN (
      SELECT target_id, count(*) AS times_seen, max(assigned_date) AS last_seen
      FROM brezzels_comment_assignments
      WHERE user_id = v_user
      GROUP BY target_id
    ) h ON h.target_id = t.id
    WHERE t.active = true
      AND NOT EXISTS (
        SELECT 1 FROM brezzels_comment_assignments a
        WHERE a.user_id = v_user AND a.assigned_date = v_today AND a.target_id = t.id
      )
    ORDER BY COALESCE(h.times_seen, 0) ASC,
             COALESCE(h.last_seen, '1970-01-01'::date) ASC,
             random()
    LIMIT v_needed
    ON CONFLICT (user_id, target_id, assigned_date) DO NOTHING;
  END IF;

  RETURN QUERY
  SELECT t.id, t.url, a.completed
  FROM brezzels_comment_assignments a
  JOIN brezzels_comment_targets t ON t.id = a.target_id
  WHERE a.user_id = v_user AND a.assigned_date = v_today
  ORDER BY a.completed ASC, a.created_at ASC;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_brezzels_comment_targets(int) TO authenticated;

INSERT INTO public.brezzels_comment_targets (url) VALUES
  ('https://app.brezzels.com/u/6avamantis9'),
  ('https://app.brezzels.com/u/_celin_k93'),
  ('https://app.brezzels.com/u/aileenluv'),
  ('https://app.brezzels.com/u/aleaest'),
  ('https://app.brezzels.com/u/alessiabellini'),
  ('https://app.brezzels.com/u/alicia_stp'),
  ('https://app.brezzels.com/u/alinaangel'),
  ('https://app.brezzels.com/u/alissaxmlr'),
  ('https://app.brezzels.com/u/aliyaa'),
  ('https://app.brezzels.com/u/amarababe'),
  ('https://app.brezzels.com/u/amberjadee'),
  ('https://app.brezzels.com/u/anastasiaaa'),
  ('https://app.brezzels.com/u/anastasiaone'),
  ('https://app.brezzels.com/u/anastasiapav'),
  ('https://app.brezzels.com/u/andre_f11_'),
  ('https://app.brezzels.com/u/ang3llov3'),
  ('https://app.brezzels.com/u/angelinaleather'),
  ('https://app.brezzels.com/u/angelique'),
  ('https://app.brezzels.com/u/angiii'),
  ('https://app.brezzels.com/u/anna_hautnah'),
  ('https://app.brezzels.com/u/annaconda'),
  ('https://app.brezzels.com/u/annagelbe'),
  ('https://app.brezzels.com/u/annahansen'),
  ('https://app.brezzels.com/u/annalena'),
  ('https://app.brezzels.com/u/annalenaaa'),
  ('https://app.brezzels.com/u/annalove_'),
  ('https://app.brezzels.com/u/annaxoxo'),
  ('https://app.brezzels.com/u/annemariaaa'),
  ('https://app.brezzels.com/u/annettestepanik'),
  ('https://app.brezzels.com/u/annihenz'),
  ('https://app.brezzels.com/u/annikaa'),
  ('https://app.brezzels.com/u/anschnapsi_1999'),
  ('https://app.brezzels.com/u/apfelsaftx3'),
  ('https://app.brezzels.com/u/arianax'),
  ('https://app.brezzels.com/u/armina.luxe'),
  ('https://app.brezzels.com/u/astormxo'),
  ('https://app.brezzels.com/u/athenareign'),
  ('https://app.brezzels.com/u/avaexklusiv'),
  ('https://app.brezzels.com/u/avapeach'),
  ('https://app.brezzels.com/u/avianna'),
  ('https://app.brezzels.com/u/aylinbreu'),
  ('https://app.brezzels.com/u/babyaurora'),
  ('https://app.brezzels.com/u/babydollie'),
  ('https://app.brezzels.com/u/babyemily'),
  ('https://app.brezzels.com/u/badbabegoere'),
  ('https://app.brezzels.com/u/badbitch_vani'),
  ('https://app.brezzels.com/u/bambi_zin001'),
  ('https://app.brezzels.com/u/barbielena'),
  ('https://app.brezzels.com/u/bavarianqueen'),
  ('https://app.brezzels.com/u/bella-cat'),
  ('https://app.brezzels.com/u/bellax'),
  ('https://app.brezzels.com/u/bibix'),
  ('https://app.brezzels.com/u/birdy01'),
  ('https://app.brezzels.com/u/blondcutegirl'),
  ('https://app.brezzels.com/u/blondercooki'),
  ('https://app.brezzels.com/u/blushykittn'),
  ('https://app.brezzels.com/u/bonafe'),
  ('https://app.brezzels.com/u/bongmodelofficial'),
  ('https://app.brezzels.com/u/britishxgirl'),
  ('https://app.brezzels.com/u/busty'),
  ('https://app.brezzels.com/u/callmemommy_00'),
  ('https://app.brezzels.com/u/camilared'),
  ('https://app.brezzels.com/u/camilaruiz'),
  ('https://app.brezzels.com/u/candycandancex'),
  ('https://app.brezzels.com/u/caramella'),
  ('https://app.brezzels.com/u/carinabuffalo'),
  ('https://app.brezzels.com/u/carinag'),
  ('https://app.brezzels.com/u/cassandramia'),
  ('https://app.brezzels.com/u/cassandraraven'),
  ('https://app.brezzels.com/u/celixvibez'),
  ('https://app.brezzels.com/u/charlyginger'),
  ('https://app.brezzels.com/u/chiaragym'),
  ('https://app.brezzels.com/u/chiarajolin'),
  ('https://app.brezzels.com/u/chrissi69vx'),
  ('https://app.brezzels.com/u/claramarie'),
  ('https://app.brezzels.com/u/claravelvet'),
  ('https://app.brezzels.com/u/clariette'),
  ('https://app.brezzels.com/u/crazybaby'),
  ('https://app.brezzels.com/u/curvylilith'),
  ('https://app.brezzels.com/u/curvyluzi'),
  ('https://app.brezzels.com/u/cutiebella'),
  ('https://app.brezzels.com/u/cutiekira'),
  ('https://app.brezzels.com/u/daliaa'),
  ('https://app.brezzels.com/u/daphnedietz'),
  ('https://app.brezzels.com/u/dariaklein'),
  ('https://app.brezzels.com/u/ddys_lil_lilith'),
  ('https://app.brezzels.com/u/deborahssecret'),
  ('https://app.brezzels.com/u/deine_elina'),
  ('https://app.brezzels.com/u/delize'),
  ('https://app.brezzels.com/u/devils_akita'),
  ('https://app.brezzels.com/u/diana_mlr'),
  ('https://app.brezzels.com/u/diekleinesuesse'),
  ('https://app.brezzels.com/u/dirtyd'),
  ('https://app.brezzels.com/u/domdaddyberlin'),
  ('https://app.brezzels.com/u/doreengnadii'),
  ('https://app.brezzels.com/u/edyta'),
  ('https://app.brezzels.com/u/einfach_kayla'),
  ('https://app.brezzels.com/u/einfachlu'),
  ('https://app.brezzels.com/u/einzelkxmpferin'),
  ('https://app.brezzels.com/u/ekaterina'),
  ('https://app.brezzels.com/u/elarablum'),
  ('https://app.brezzels.com/u/elenorarose'),
  ('https://app.brezzels.com/u/elgroh'),
  ('https://app.brezzels.com/u/elin98'),
  ('https://app.brezzels.com/u/elisee'),
  ('https://app.brezzels.com/u/elisfey1'),
  ('https://app.brezzels.com/u/ellabluem'),
  ('https://app.brezzels.com/u/ellaumbrella'),
  ('https://app.brezzels.com/u/elli13'),
  ('https://app.brezzels.com/u/emilia_lee'),
  ('https://app.brezzels.com/u/emilynow'),
  ('https://app.brezzels.com/u/emilystern'),
  ('https://app.brezzels.com/u/emma01'),
  ('https://app.brezzels.com/u/emma_rose'),
  ('https://app.brezzels.com/u/emmabraun'),
  ('https://app.brezzels.com/u/ennaa'),
  ('https://app.brezzels.com/u/erikaa264'),
  ('https://app.brezzels.com/u/eunice'),
  ('https://app.brezzels.com/u/evamonell'),
  ('https://app.brezzels.com/u/evry'),
  ('https://app.brezzels.com/u/exclusive_ella'),
  ('https://app.brezzels.com/u/eyeporn'),
  ('https://app.brezzels.com/u/faithcarter'),
  ('https://app.brezzels.com/u/falk_fettsack4life'),
  ('https://app.brezzels.com/u/fayeflame'),
  ('https://app.brezzels.com/u/feederella'),
  ('https://app.brezzels.com/u/feetdreamsaremadeofthese'),
  ('https://app.brezzels.com/u/fiftyflamex'),
  ('https://app.brezzels.com/u/fine226'),
  ('https://app.brezzels.com/u/fitkatycom'),
  ('https://app.brezzels.com/u/freakyceline'),
  ('https://app.brezzels.com/u/freche-lisa'),
  ('https://app.brezzels.com/u/frecklesgirl'),
  ('https://app.brezzels.com/u/fuss'),
  ('https://app.brezzels.com/u/geileweinrebe'),
  ('https://app.brezzels.com/u/geldherrin1313'),
  ('https://app.brezzels.com/u/ghislainevaleriey'),
  ('https://app.brezzels.com/u/gianna_'),
  ('https://app.brezzels.com/u/ginger24'),
  ('https://app.brezzels.com/u/girina'),
  ('https://app.brezzels.com/u/girlalex'),
  ('https://app.brezzels.com/u/girlfriendnextdoor'),
  ('https://app.brezzels.com/u/goldenpeach'),
  ('https://app.brezzels.com/u/goldi159'),
  ('https://app.brezzels.com/u/hannahshy'),
  ('https://app.brezzels.com/u/hannahsweet'),
  ('https://app.brezzels.com/u/happyfeet1991'),
  ('https://app.brezzels.com/u/heissediva'),
  ('https://app.brezzels.com/u/helen'),
  ('https://app.brezzels.com/u/helenahartmann'),
  ('https://app.brezzels.com/u/helenna'),
  ('https://app.brezzels.com/u/highfem'),
  ('https://app.brezzels.com/u/hildavalentine'),
  ('https://app.brezzels.com/u/hollydoesstretching'),
  ('https://app.brezzels.com/u/honeyandheat'),
  ('https://app.brezzels.com/u/honeygirl'),
  ('https://app.brezzels.com/u/hot-marons'),
  ('https://app.brezzels.com/u/hotgirl__88'),
  ('https://app.brezzels.com/u/hotinkedgirl_99'),
  ('https://app.brezzels.com/u/hottiemila'),
  ('https://app.brezzels.com/u/iamdani'),
  ('https://app.brezzels.com/u/icyyxxx'),
  ('https://app.brezzels.com/u/ilayla'),
  ('https://app.brezzels.com/u/ilma'),
  ('https://app.brezzels.com/u/inkedadventurer'),
  ('https://app.brezzels.com/u/inkedbabe99'),
  ('https://app.brezzels.com/u/inkedchany'),
  ('https://app.brezzels.com/u/isabellaklug'),
  ('https://app.brezzels.com/u/itscelly'),
  ('https://app.brezzels.com/u/itsivy'),
  ('https://app.brezzels.com/u/itsmejihane'),
  ('https://app.brezzels.com/u/itsofficalvicky96'),
  ('https://app.brezzels.com/u/ivannabelle'),
  ('https://app.brezzels.com/u/jamiedreams'),
  ('https://app.brezzels.com/u/janinasummer'),
  ('https://app.brezzels.com/u/janinayoussefian'),
  ('https://app.brezzels.com/u/janineof24'),
  ('https://app.brezzels.com/u/jasiashi'),
  ('https://app.brezzels.com/u/jasmin_de_haan'),
  ('https://app.brezzels.com/u/jasminwhite'),
  ('https://app.brezzels.com/u/jayjay_lost'),
  ('https://app.brezzels.com/u/jayjaypink'),
  ('https://app.brezzels.com/u/jen_nyy_'),
  ('https://app.brezzels.com/u/jenlolo'),
  ('https://app.brezzels.com/u/jenna_'),
  ('https://app.brezzels.com/u/jenna_lia'),
  ('https://app.brezzels.com/u/jenni22'),
  ('https://app.brezzels.com/u/jenniferlu'),
  ('https://app.brezzels.com/u/jessicaadam'),
  ('https://app.brezzels.com/u/jessicalane'),
  ('https://app.brezzels.com/u/jessicalux'),
  ('https://app.brezzels.com/u/jessiiii'),
  ('https://app.brezzels.com/u/jill'),
  ('https://app.brezzels.com/u/jindo109'),
  ('https://app.brezzels.com/u/joanaelaa'),
  ('https://app.brezzels.com/u/joesignon'),
  ('https://app.brezzels.com/u/joleen19'),
  ('https://app.brezzels.com/u/jolieee'),
  ('https://app.brezzels.com/u/josie44'),
  ('https://app.brezzels.com/u/josihere'),
  ('https://app.brezzels.com/u/joyce-ang'),
  ('https://app.brezzels.com/u/juicyjolina'),
  ('https://app.brezzels.com/u/julia_dom'),
  ('https://app.brezzels.com/u/juliadaheim'),
  ('https://app.brezzels.com/u/just18'),
  ('https://app.brezzels.com/u/jxsmin'),
  ('https://app.brezzels.com/u/kallathepet'),
  ('https://app.brezzels.com/u/kateryna'),
  ('https://app.brezzels.com/u/katerynasvibes'),
  ('https://app.brezzels.com/u/kateyquinnxx'),
  ('https://app.brezzels.com/u/katharinax'),
  ('https://app.brezzels.com/u/kati93'),
  ('https://app.brezzels.com/u/katjaschmidt2020'),
  ('https://app.brezzels.com/u/kaylaskyy'),
  ('https://app.brezzels.com/u/keksi_'),
  ('https://app.brezzels.com/u/kendra_malta'),
  ('https://app.brezzels.com/u/keyusha'),
  ('https://app.brezzels.com/u/kim_ic'),
  ('https://app.brezzels.com/u/kirakarter'),
  ('https://app.brezzels.com/u/kisslana'),
  ('https://app.brezzels.com/u/kitty05'),
  ('https://app.brezzels.com/u/kmimimiii'),
  ('https://app.brezzels.com/u/ksenia'),
  ('https://app.brezzels.com/u/kyanova_gym'),
  ('https://app.brezzels.com/u/kylie_rose'),
  ('https://app.brezzels.com/u/lady_tamina'),
  ('https://app.brezzels.com/u/ladycherry'),
  ('https://app.brezzels.com/u/ladydana'),
  ('https://app.brezzels.com/u/lana69'),
  ('https://app.brezzels.com/u/lara11'),
  ('https://app.brezzels.com/u/larafuchs'),
  ('https://app.brezzels.com/u/laralou'),
  ('https://app.brezzels.com/u/larasophiiiee'),
  ('https://app.brezzels.com/u/larisst'),
  ('https://app.brezzels.com/u/laura_etw'),
  ('https://app.brezzels.com/u/laurawks'),
  ('https://app.brezzels.com/u/lea_katz'),
  ('https://app.brezzels.com/u/leacute'),
  ('https://app.brezzels.com/u/leawhite'),
  ('https://app.brezzels.com/u/leawinter'),
  ('https://app.brezzels.com/u/leefeeteellaa'),
  ('https://app.brezzels.com/u/leia'),
  ('https://app.brezzels.com/u/lena_lehmann'),
  ('https://app.brezzels.com/u/lenaliebe'),
  ('https://app.brezzels.com/u/lenameier'),
  ('https://app.brezzels.com/u/lenaschoelling'),
  ('https://app.brezzels.com/u/lenasummer'),
  ('https://app.brezzels.com/u/leni_fuchs'),
  ('https://app.brezzels.com/u/lenilovee'),
  ('https://app.brezzels.com/u/leon062001'),
  ('https://app.brezzels.com/u/leoniegelbe'),
  ('https://app.brezzels.com/u/leoniesommer'),
  ('https://app.brezzels.com/u/lera4ka'),
  ('https://app.brezzels.com/u/lexigo'),
  ('https://app.brezzels.com/u/lia_me'),
  ('https://app.brezzels.com/u/liaa'),
  ('https://app.brezzels.com/u/liagym'),
  ('https://app.brezzels.com/u/liaschmidt'),
  ('https://app.brezzels.com/u/lilly69'),
  ('https://app.brezzels.com/u/lillybby'),
  ('https://app.brezzels.com/u/lillyemma'),
  ('https://app.brezzels.com/u/lilyyyy'),
  ('https://app.brezzels.com/u/lin_lia93'),
  ('https://app.brezzels.com/u/lina_winter'),
  ('https://app.brezzels.com/u/linaa'),
  ('https://app.brezzels.com/u/linaamara'),
  ('https://app.brezzels.com/u/linakaribika'),
  ('https://app.brezzels.com/u/linalovely'),
  ('https://app.brezzels.com/u/linaobession'),
  ('https://app.brezzels.com/u/linarhoades'),
  ('https://app.brezzels.com/u/linas_secret'),
  ('https://app.brezzels.com/u/lingeriena'),
  ('https://app.brezzels.com/u/linzkicode'),
  ('https://app.brezzels.com/u/lis_a05'),
  ('https://app.brezzels.com/u/lisabella'),
  ('https://app.brezzels.com/u/lisali69c'),
  ('https://app.brezzels.com/u/lisalure'),
  ('https://app.brezzels.com/u/lisamariee'),
  ('https://app.brezzels.com/u/lisaslove'),
  ('https://app.brezzels.com/u/lisavey'),
  ('https://app.brezzels.com/u/lisavibesonly'),
  ('https://app.brezzels.com/u/littlebigbear'),
  ('https://app.brezzels.com/u/littlemila'),
  ('https://app.brezzels.com/u/liv_gymnastic'),
  ('https://app.brezzels.com/u/livia'),
  ('https://app.brezzels.com/u/livwildborn'),
  ('https://app.brezzels.com/u/liz25'),
  ('https://app.brezzels.com/u/lola011956'),
  ('https://app.brezzels.com/u/lolajohanna'),
  ('https://app.brezzels.com/u/lolalix'),
  ('https://app.brezzels.com/u/lolalove'),
  ('https://app.brezzels.com/u/love_kiitsune'),
  ('https://app.brezzels.com/u/lovelyschneeflocke'),
  ('https://app.brezzels.com/u/lovlyluna'),
  ('https://app.brezzels.com/u/lsbitch'),
  ('https://app.brezzels.com/u/lu_isalicious'),
  ('https://app.brezzels.com/u/lu_isalicious93'),
  ('https://app.brezzels.com/u/luanalove'),
  ('https://app.brezzels.com/u/lucien'),
  ('https://app.brezzels.com/u/lucy'),
  ('https://app.brezzels.com/u/lucy_jane'),
  ('https://app.brezzels.com/u/lucy_nunez'),
  ('https://app.brezzels.com/u/luisaloves'),
  ('https://app.brezzels.com/u/lunababy'),
  ('https://app.brezzels.com/u/lunaj'),
  ('https://app.brezzels.com/u/lunalushx'),
  ('https://app.brezzels.com/u/lunamai'),
  ('https://app.brezzels.com/u/lunavelvet'),
  ('https://app.brezzels.com/u/lunawolf'),
  ('https://app.brezzels.com/u/lunnixi'),
  ('https://app.brezzels.com/u/luvea'),
  ('https://app.brezzels.com/u/lxabslr'),
  ('https://app.brezzels.com/u/lxonixchk517'),
  ('https://app.brezzels.com/u/lynn_marmalade'),
  ('https://app.brezzels.com/u/m_elina_2007'),
  ('https://app.brezzels.com/u/madamekrawall'),
  ('https://app.brezzels.com/u/madamemarie'),
  ('https://app.brezzels.com/u/madamevice'),
  ('https://app.brezzels.com/u/madeleine99'),
  ('https://app.brezzels.com/u/madeline'),
  ('https://app.brezzels.com/u/madison_yourbaby'),
  ('https://app.brezzels.com/u/madisonlanez'),
  ('https://app.brezzels.com/u/maia'),
  ('https://app.brezzels.com/u/majahier'),
  ('https://app.brezzels.com/u/majameer'),
  ('https://app.brezzels.com/u/malee_'),
  ('https://app.brezzels.com/u/malisaa'),
  ('https://app.brezzels.com/u/malou'),
  ('https://app.brezzels.com/u/mandyjane'),
  ('https://app.brezzels.com/u/mandyrose'),
  ('https://app.brezzels.com/u/maniapigmilk'),
  ('https://app.brezzels.com/u/margitx2'),
  ('https://app.brezzels.com/u/maria05'),
  ('https://app.brezzels.com/u/mariedevis'),
  ('https://app.brezzels.com/u/mariejayy'),
  ('https://app.brezzels.com/u/marilove'),
  ('https://app.brezzels.com/u/marry_me'),
  ('https://app.brezzels.com/u/marvinjoseramos'),
  ('https://app.brezzels.com/u/marynuska'),
  ('https://app.brezzels.com/u/maryrain'),
  ('https://app.brezzels.com/u/matjen25'),
  ('https://app.brezzels.com/u/mauss'),
  ('https://app.brezzels.com/u/meggiejolie'),
  ('https://app.brezzels.com/u/meisingerfotografie'),
  ('https://app.brezzels.com/u/melinamoon'),
  ('https://app.brezzels.com/u/meliriveira'),
  ('https://app.brezzels.com/u/melissa_hot'),
  ('https://app.brezzels.com/u/meliweber'),
  ('https://app.brezzels.com/u/melly2020'),
  ('https://app.brezzels.com/u/melnoir'),
  ('https://app.brezzels.com/u/miahase'),
  ('https://app.brezzels.com/u/mialynn'),
  ('https://app.brezzels.com/u/michelle1802'),
  ('https://app.brezzels.com/u/midnight'),
  ('https://app.brezzels.com/u/mila_'),
  ('https://app.brezzels.com/u/mila_free'),
  ('https://app.brezzels.com/u/mila_rose'),
  ('https://app.brezzels.com/u/miladreams'),
  ('https://app.brezzels.com/u/milarose66'),
  ('https://app.brezzels.com/u/milax'),
  ('https://app.brezzels.com/u/milrosee'),
  ('https://app.brezzels.com/u/mimi_europ'),
  ('https://app.brezzels.com/u/mimi_studio_design'),
  ('https://app.brezzels.com/u/mimiangel'),
  ('https://app.brezzels.com/u/mimicute'),
  ('https://app.brezzels.com/u/miss_akin'),
  ('https://app.brezzels.com/u/miss_ruthi'),
  ('https://app.brezzels.com/u/missequis'),
  ('https://app.brezzels.com/u/misses_b'),
  ('https://app.brezzels.com/u/misstoes69'),
  ('https://app.brezzels.com/u/miumeory'),
  ('https://app.brezzels.com/u/mona25'),
  ('https://app.brezzels.com/u/mona66'),
  ('https://app.brezzels.com/u/monademure'),
  ('https://app.brezzels.com/u/morena'),
  ('https://app.brezzels.com/u/mrsna'),
  ('https://app.brezzels.com/u/mrsnadine'),
  ('https://app.brezzels.com/u/ms_shorty'),
  ('https://app.brezzels.com/u/mygirl'),
  ('https://app.brezzels.com/u/nastybelle'),
  ('https://app.brezzels.com/u/nastywithclasses'),
  ('https://app.brezzels.com/u/naturalaura'),
  ('https://app.brezzels.com/u/naughtycarolinaaa'),
  ('https://app.brezzels.com/u/nekyro'),
  ('https://app.brezzels.com/u/nessykiss'),
  ('https://app.brezzels.com/u/netty23'),
  ('https://app.brezzels.com/u/nici1616'),
  ('https://app.brezzels.com/u/nicisecret11'),
  ('https://app.brezzels.com/u/niclas7728'),
  ('https://app.brezzels.com/u/nightofthejumps'),
  ('https://app.brezzels.com/u/nikaakita'),
  ('https://app.brezzels.com/u/nikki_ink'),
  ('https://app.brezzels.com/u/nikkiblondie'),
  ('https://app.brezzels.com/u/nikkky'),
  ('https://app.brezzels.com/u/ninaclara'),
  ('https://app.brezzels.com/u/ninarae'),
  ('https://app.brezzels.com/u/ninasweet'),
  ('https://app.brezzels.com/u/nurliyax'),
  ('https://app.brezzels.com/u/official.emmarichter'),
  ('https://app.brezzels.com/u/oliviajane'),
  ('https://app.brezzels.com/u/only_linaa'),
  ('https://app.brezzels.com/u/onlyblondixx'),
  ('https://app.brezzels.com/u/onlyfarina'),
  ('https://app.brezzels.com/u/onlylia'),
  ('https://app.brezzels.com/u/patty0308'),
  ('https://app.brezzels.com/u/paulasun'),
  ('https://app.brezzels.com/u/paulinaa'),
  ('https://app.brezzels.com/u/peach'),
  ('https://app.brezzels.com/u/phoebexx'),
  ('https://app.brezzels.com/u/pia-victoria'),
  ('https://app.brezzels.com/u/piachanelii'),
  ('https://app.brezzels.com/u/piadoctor'),
  ('https://app.brezzels.com/u/pinkminttt'),
  ('https://app.brezzels.com/u/pinkymarie'),
  ('https://app.brezzels.com/u/porsche_bmw_girly'),
  ('https://app.brezzels.com/u/powerpuffgirl'),
  ('https://app.brezzels.com/u/primary-termite31'),
  ('https://app.brezzels.com/u/princessofboots'),
  ('https://app.brezzels.com/u/prvt_lini'),
  ('https://app.brezzels.com/u/pureasfxck'),
  ('https://app.brezzels.com/u/queeniii'),
  ('https://app.brezzels.com/u/queenvictoria'),
  ('https://app.brezzels.com/u/realela18'),
  ('https://app.brezzels.com/u/reallea'),
  ('https://app.brezzels.com/u/red_rose'),
  ('https://app.brezzels.com/u/redfoxxx'),
  ('https://app.brezzels.com/u/redgirl88'),
  ('https://app.brezzels.com/u/redleaa'),
  ('https://app.brezzels.com/u/rigina'),
  ('https://app.brezzels.com/u/roaandfans'),
  ('https://app.brezzels.com/u/ronja_life'),
  ('https://app.brezzels.com/u/rosie_fox'),
  ('https://app.brezzels.com/u/rosy'),
  ('https://app.brezzels.com/u/roxi_black'),
  ('https://app.brezzels.com/u/ruubichan'),
  ('https://app.brezzels.com/u/sabine2612'),
  ('https://app.brezzels.com/u/sabso'),
  ('https://app.brezzels.com/u/sallyysweetheart'),
  ('https://app.brezzels.com/u/samanthax'),
  ('https://app.brezzels.com/u/samicheeks'),
  ('https://app.brezzels.com/u/sandy-lou'),
  ('https://app.brezzels.com/u/sandy6'),
  ('https://app.brezzels.com/u/sandycandyy'),
  ('https://app.brezzels.com/u/sara_sinaidaa'),
  ('https://app.brezzels.com/u/sarah1047868'),
  ('https://app.brezzels.com/u/sarah_seroquel'),
  ('https://app.brezzels.com/u/sarahann_official'),
  ('https://app.brezzels.com/u/sarawagner'),
  ('https://app.brezzels.com/u/sasamagdy8'),
  ('https://app.brezzels.com/u/scarlettsore'),
  ('https://app.brezzels.com/u/scoraja'),
  ('https://app.brezzels.com/u/secretblondie'),
  ('https://app.brezzels.com/u/secretlola'),
  ('https://app.brezzels.com/u/secretmarie'),
  ('https://app.brezzels.com/u/secretmila'),
  ('https://app.brezzels.com/u/seli03yasi'),
  ('https://app.brezzels.com/u/selina_'),
  ('https://app.brezzels.com/u/seraphyne'),
  ('https://app.brezzels.com/u/sexy_katalinka'),
  ('https://app.brezzels.com/u/sexy_mia_wild'),
  ('https://app.brezzels.com/u/sexyangel'),
  ('https://app.brezzels.com/u/sexygirl69'),
  ('https://app.brezzels.com/u/sexynelly'),
  ('https://app.brezzels.com/u/sexyredpacy'),
  ('https://app.brezzels.com/u/sexyxena'),
  ('https://app.brezzels.com/u/shorty_anushka'),
  ('https://app.brezzels.com/u/sidecutevici'),
  ('https://app.brezzels.com/u/siera'),
  ('https://app.brezzels.com/u/silasrothenbuehler'),
  ('https://app.brezzels.com/u/silviax'),
  ('https://app.brezzels.com/u/simonvomberge'),
  ('https://app.brezzels.com/u/simply_lee'),
  ('https://app.brezzels.com/u/sinamausi'),
  ('https://app.brezzels.com/u/skinnygirl'),
  ('https://app.brezzels.com/u/skinnysofie'),
  ('https://app.brezzels.com/u/skyly'),
  ('https://app.brezzels.com/u/slavicdoll'),
  ('https://app.brezzels.com/u/slow-tarsier15'),
  ('https://app.brezzels.com/u/sofiemaarieee'),
  ('https://app.brezzels.com/u/softblondie'),
  ('https://app.brezzels.com/u/sonic_laserweiss_fabia'),
  ('https://app.brezzels.com/u/sophiasnow'),
  ('https://app.brezzels.com/u/sophie_sch'),
  ('https://app.brezzels.com/u/sophies_content'),
  ('https://app.brezzels.com/u/sophievombau'),
  ('https://app.brezzels.com/u/sophiexo'),
  ('https://app.brezzels.com/u/sophiexox'),
  ('https://app.brezzels.com/u/sophiexvr'),
  ('https://app.brezzels.com/u/sophiiesummer'),
  ('https://app.brezzels.com/u/soulsally'),
  ('https://app.brezzels.com/u/spicegirl69'),
  ('https://app.brezzels.com/u/spotthefine1'),
  ('https://app.brezzels.com/u/stella_sunshine'),
  ('https://app.brezzels.com/u/stilleswasserx'),
  ('https://app.brezzels.com/u/strongandsavage'),
  ('https://app.brezzels.com/u/sugarsole'),
  ('https://app.brezzels.com/u/svonne'),
  ('https://app.brezzels.com/u/sweet-girl87'),
  ('https://app.brezzels.com/u/sweet_milena'),
  ('https://app.brezzels.com/u/sweet_n_spicy'),
  ('https://app.brezzels.com/u/sweet_soxx'),
  ('https://app.brezzels.com/u/sweetanna'),
  ('https://app.brezzels.com/u/sweetclairy99'),
  ('https://app.brezzels.com/u/sweetelisa'),
  ('https://app.brezzels.com/u/sweetlilly'),
  ('https://app.brezzels.com/u/sweetpoli'),
  ('https://app.brezzels.com/u/sweetsvenja'),
  ('https://app.brezzels.com/u/swettykatty'),
  ('https://app.brezzels.com/u/swissoli'),
  ('https://app.brezzels.com/u/tamy-love'),
  ('https://app.brezzels.com/u/tanschi'),
  ('https://app.brezzels.com/u/taraxmitchell'),
  ('https://app.brezzels.com/u/tasia'),
  ('https://app.brezzels.com/u/tattoo-babe'),
  ('https://app.brezzels.com/u/themaskgirl'),
  ('https://app.brezzels.com/u/thesimplelifeoflola'),
  ('https://app.brezzels.com/u/tiaflexxx'),
  ('https://app.brezzels.com/u/tin_chen87'),
  ('https://app.brezzels.com/u/tina.tinkabelll'),
  ('https://app.brezzels.com/u/tinygirl'),
  ('https://app.brezzels.com/u/tompfeiffer_mtb'),
  ('https://app.brezzels.com/u/transfraujanine'),
  ('https://app.brezzels.com/u/trinity69'),
  ('https://app.brezzels.com/u/vaiana_moon'),
  ('https://app.brezzels.com/u/valeria'),
  ('https://app.brezzels.com/u/valeriestar'),
  ('https://app.brezzels.com/u/valery'),
  ('https://app.brezzels.com/u/vanessacontent'),
  ('https://app.brezzels.com/u/venera'),
  ('https://app.brezzels.com/u/vennababy'),
  ('https://app.brezzels.com/u/vibesflow'),
  ('https://app.brezzels.com/u/vic1401'),
  ('https://app.brezzels.com/u/vicky'),
  ('https://app.brezzels.com/u/vikiblond'),
  ('https://app.brezzels.com/u/viviennee'),
  ('https://app.brezzels.com/u/voluptabelle'),
  ('https://app.brezzels.com/u/x_chaosqueen_x'),
  ('https://app.brezzels.com/u/x_mxa'),
  ('https://app.brezzels.com/u/xari'),
  ('https://app.brezzels.com/u/xbabymarie'),
  ('https://app.brezzels.com/u/xdenise66'),
  ('https://app.brezzels.com/u/xhoneyfeet'),
  ('https://app.brezzels.com/u/xlaura'),
  ('https://app.brezzels.com/u/xlenaxveil'),
  ('https://app.brezzels.com/u/xlucyx'),
  ('https://app.brezzels.com/u/xmarielust'),
  ('https://app.brezzels.com/u/xoxocurly'),
  ('https://app.brezzels.com/u/xtabea'),
  ('https://app.brezzels.com/u/xyourcrushx'),
  ('https://app.brezzels.com/u/xzaikaa'),
  ('https://app.brezzels.com/u/yaraivana'),
  ('https://app.brezzels.com/u/yourbadgirlmarie'),
  ('https://app.brezzels.com/u/yourfavouritebabygirl'),
  ('https://app.brezzels.com/u/yukiama'),
  ('https://app.brezzels.com/u/yvi84'),
  ('https://app.brezzels.com/u/zimtschnecke123'),
  ('https://app.brezzels.com/u/zoeyparker')
ON CONFLICT (url) DO NOTHING;